version: '2'

services:

  rails:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./script/start
    volumes:
      - .:/var/www/fender-auth
    volumes_from:
      - box
    ports:
      - '3000:3000'
    links:
      - db
    stdin_open: true
    tty: true

  box:
    image: busybox
    volumes:
      - /box

  db:
    image: postgres:9.6
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres:
