default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  host: <%= ENV.fetch('POSTGRES_HOST') %>
  username: <%= ENV.fetch('POSTGRES_USER') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD') %>

development:
  <<: *default
  database: fenderauth_development

test: &test
  <<: *default
  database: fenderauth_test

production:
  <<: *default
  database: fenderauth_production
  password: <%= ENV.fetch('FENDER_AUTH_DATABASE_PASSWORD') %>

cucumber:
  <<: *test
